name: Generate snake animation

on:
  schedule:
    - cron: "*/1 * * * *"

  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install svgwrite

      - name: Generate snake.svg
        run: |
          python generate_snake.py --dark-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add snake.svg
          git commit -m "Update snake.svg to dark mode"
          git push
